[package]
name = "frontend"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
futures = "0"
gloo = "0"
gloo-console = "0"
reqwasm = "0"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
wasm-bindgen-futures = "0"
yew = "0.18"
ybc = "0.2"
