[package]
name = "app"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
futures = "0"
gloo = "0"
gloo-utils = "0"
log = "0"
models = { path = "../models" }
reqwasm = "0"
wasm-bindgen-futures = "0"
wasm-logger = "0"
wee_alloc = "0"
yew = "0.19"
yew-router = "0.16"
