[package]
name = "app"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
futures = "0"
gloo = "0"
gloo-console = "0"
models = { path = "../models" }
reqwasm = "0"
wasm-bindgen-futures = "0"
wee_alloc = "0"
yew = "0.18"
ybc = "0.2"
